version: "3.5"

services:

    backend:
        image: 23_back
        restart: unless-stopped
        ports:
          - 8000:8000
        volumes:
          - ./logs.txt:/logs.txt
        environment:
          - REDIS=redis

    frontend:
        image: 23_front
        ports:
          - 5000:5000

    redis:
        image: redis
        restart: unless-stopped
        ports:
          -  6379:6379
