FROM ubuntu:16.04

EXPOSE 8000

RUN useradd -m app

COPY --chown=app ./backend-example-docker /app/

WORKDIR /app/

RUN apt-get update && \
    apt-get install -y curl ca-certificates && \
    curl -sL https://deb.nodesource.com/setup_10.x | bash && \
    apt-get install -y nodejs && \
    npm install && \
    apt-get purge -y --auto-remove curl && \
    rm -rf /var/lib/apt/lists/*

USER app

CMD FRONT_URL=http://localhost:5000 npm start
