version: "3.5"

services:

    backend:
        image: 23_back
        restart: unless-stopped
        ports:
          - 8000:8000
        environment:
          - REDIS=redis-server
          - DB_USERNAME=testiuser
          - DB_PASSWORD=testipass
          - DB_NAME=psql_db
          - DB_HOST=psql_db
          - VIRTUAL_HOST=backend-example.local

    frontend:
        image: 23_front
        ports:
          - 5000:5000
        environment:
          - VIRTUAL_HOST=frontend-example.local


    redis:
        image: redis
        hostname: redis-server
        container_name: redis-server
        restart: unless-stopped
        ports:
          -  6379:6379

    psql_db:
        image: postgres
        container_name: psql
        restart: unless-stopped
        environment:
          - POSTGRES_PASSWORD=testipass
          - POSTGRES_USER=testiuser
          - POSTGRES_DB=psql_db

    reverse_proxy:
        image: jwilder/nginx-proxy
        restart: unless-stopped
        depends_on:
          - backend
          - frontend
        ports:
          - 80:80
        volumes:
          - /var/run/docker.sock:/tmp/docker.sock:ro
          - ./nginx.conf:/etc/nginx/nginx.conf
